### PR TITLE
Fix conversion of market price in reference currency

### LINKED ISSUE #24: reference currency conversion
At the moment we not supporting converting to a reference currency (ie. FIAT).

What we should do is mapping market to specific formula with URL

Example:

We have a pair like COIN-USDt, where COIN is any asset that is not "stable" in value against FIAT (like L-BTC)  we know that to get the reference price in EUR for each we need 

1. convert base asset to quote asset (using latest price for that market we have locally)
2. convert quote asset to chosen fiat currency using a dedicated external price feed URL 

The conversion is still valid if the quote asset is not a stablecoin, we only need to be sure there is a direct price feed QUOTE > FIAT, if not we can't return reference price conversion (maybe we should return empty?)

### LINKED ISSUE #32: fix reference price not converting base/quote asset in kind
The purpose of the `reference_{base,quote}_price` field is to simply show the amount `{base,quote}_price` converted against a well known price feed.

Take into consideration most of the time it will happen the base asset has no direct exchange rate somewhere else, so it must be converted to quote price first and calculate proportionally.

### PR DESCRIPTION
**Pull request by altafan**
This fixes the conversion of markets' prices to reference currency for those containing a stable coin as base or quote asset.

Closes #24 
Closes #32 

Please @tiero @sekulicd review this.

### CODE REVIEW

**Comment by altafan** [comment]
@sekulicd I didn't touch anything about market balance but for some reason some of the tests are failing.

And also tests about MarketsPrice are failing even if i didn't change the fixtures. Can you help me figuring this out in order to make the CI pass?

**Comment by altafan** [comment]
@tiero Done! I had to make some fixes to the rate service impl. I had to fix also the rater service imp and more importantly its tests. There, there are a lot of tests for exported and unexported functions, but unfortunately, there were some mistakes.

I'll eventually check and fix all remaining tests in a later PR.

File: internal/core/application/market_price_service.go [hunk 1]
```diff
@@ -145,122 +150,100 @@ func (m *marketPriceService) GetPrices(
...
-		ctx,
-		baseCurrency,
-		referenceCurrency,
-	)
-	if err != nil {
-		if err == port.ErrCurrencyNotFound {
-			baseConvertable = false
-		} else {
-			return decimal.Zero, false, decimal.Zero, false, err
+	isBaseAssetStable, _ := m.raterSvc.IsFiatSymbolSupported(baseAssetTicker)
```
Comment (sekulicd) [inline internal/core/application/market_price_service.go:176]: @altafan why dont we handle errors?

Comment (altafan) [reply internal/core/application/market_price_service.go:176]: not necessary to return error here. The value of such vars is used just to understand which of the 2 prices to convert to ref currency and which one will be calculated instead.
In case both are recognized as non-stable coins the service still attempts to retrieve the price in ref currency without "passing from" a stable coin.

**Comment by sekulicd** [comment]
> @sekulicd I didn't touch anything about market balance but for some reason some of the tests are failing.
> 
> And also tests about MarketsPrice are failing even if i didn't change the fixtures. Can you help me figuring this out in order to make the CI pass?

Fixed with latest commit. @tiero @altafan 
Rest LGTM.
